namespace DungeonCrawler.API.Models;

/// <summary>
/// Represents a player account (durable identity).
/// Maps to the 'accounts' table in Postgres.
/// </summary>
public class Account
{
    /// <summary>
    /// Unique identifier for this account.
    /// Auto-generated by Postgres SERIAL.
    /// </summary>
    public int AccountId { get; set; }

    /// <summary>
    /// Player's chosen username (max 32 chars).
    /// Must be unique across all accounts.
    /// </summary>
    public required string Username { get; set; }

    /// <summary>
    /// Bcrypt or Argon2 hash of the player's password.
    /// Password itself is never stored.
    /// </summary>
    public required string PasswordHash { get; set; }

    /// <summary>
    /// When this account was created (UTC).
    /// Set by the database on insert.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Navigation property: each account has one player progression record.
    /// This represents the player's level, XP, gold, HP, etc.
    /// </summary>
    public PlayerProgress? PlayerProgress { get; set; }

    /// <summary>
    /// Navigation property: accepted/completed quests for this player.
    /// </summary>
    public ICollection<PlayerQuest> PlayerQuests { get; set; } = [];

    /// <summary>
    /// Navigation property: inventory items owned by this player.
    /// </summary>
    public ICollection<InventoryItem> InventoryItems { get; set; } = [];

    /// <summary>
    /// Navigation property: chat messages authored by this player in the hub.
    /// </summary>
    public ICollection<HubChatMessage> HubChatMessages { get; set; } = [];
}
