namespace DungeonCrawler.API.Models;

/// <summary>
/// Represents a message sent in the hub overworld chat.
/// Stored durably so late-joining players can load recent context.
/// </summary>
public class HubChatMessage
{
    /// <summary>
    /// Surrogate key generated by Postgres.
    /// </summary>
    public long HubChatMessageId { get; set; }

    /// <summary>
    /// Account that authored the message.
    /// </summary>
    public int AccountId { get; set; }

    /// <summary>
    /// Message payload shown to players.
    /// </summary>
    public required string Message { get; set; }

    /// <summary>
    /// UTC timestamp for ordering and display.
    /// </summary>
    public DateTime SentAt { get; set; }

    /// <summary>
    /// Navigation to sender account.
    /// </summary>
    public Account? Account { get; set; }
}
