apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dungeon-crawler-api
  namespace: dungeon-crawler
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: dungeon.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dungeon-crawler-api
                port:
                  number: 80