apiVersion: v1
kind: Secret
metadata:
  name: dungeon-crawler-api-secrets
  namespace: dungeon-crawler
type: Opaque
stringData:
  ConnectionStrings__DungeonCrawlerDb: Host=postgres-service;Port=5432;Database=dungeoncrawler;Username=postgres;Password=replace-me