apiVersion: v1
kind: Service
metadata:
  name: dungeon-crawler-frontend
  namespace: dungeon-crawler
spec:
  selector:
    app: dungeon-crawler-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080